task_id: free_text_acme_hqhs_006
status: ready
description: 'HQHS: What is the total loss by claim number?'
prompts:
- key: base
  prompt: 'What is the total loss of each claim by claim number where total loss is
    the sum of loss payment, loss reserve, expense payment, expense reserve amount?


    Write a model called result.sql containing your answer.'
- key: with_sl
  prompt: 'Using the dbt semantic layer, answer this question:


    What is the total loss of each claim by claim number where total loss is the sum
    of loss payment, loss reserve, expense payment, expense reserve amount?


    Write a model called result.sql containing your answer.'
author_name: dbt-labs
author_email: noreply@getdbt.com
difficulty: hard
tags:
- semantic-layer
- metricflow
- free-text
- acme-insurance
- hqhs
test_setup: dbt run --select result
solution_seeds:
- table_name: result
variants:
- db_type: duckdb
  db_name: acme_insurance
  project_type: dbt
  project_name: acme_insurance
