task_id: free_text_acme_hqls_010
status: ready
description: 'HQLS: Policy'
prompts:
- key: base
  prompt: 'How many policies do we have?


    Write a model called result.sql containing your answer.'
- key: with_sl
  prompt: 'Using the dbt semantic layer, answer this question:


    How many policies do we have?


    Write a model called result.sql containing your answer.'
author_name: dbt-labs
author_email: noreply@getdbt.com
difficulty: easy
tags:
- semantic-layer
- metricflow
- free-text
- acme-insurance
- hqls
test_setup: dbt run --select result
solution_seeds:
- table_name: result
variants:
- db_type: duckdb
  db_name: acme_insurance
  project_type: dbt
  project_name: acme_insurance
