task_id: free_text_acme_lqls_007
status: ready
description: 'LQLS: Policy - Agent'
prompts:
- key: base
  prompt: 'Return all the policies and the agents that sold them by policy number
    and agent id


    Write a model called result.sql containing your answer.'
- key: with_sl
  prompt: 'Using the dbt semantic layer, answer this question:


    Return all the policies and the agents that sold them by policy number and agent
    id


    Write a model called result.sql containing your answer.'
author_name: dbt-labs
author_email: noreply@getdbt.com
difficulty: easy
tags:
- semantic-layer
- metricflow
- free-text
- acme-insurance
- lqls
test_setup: dbt run --select result
solution_seeds:
- table_name: result
variants:
- db_type: duckdb
  db_name: acme_insurance
  project_type: dbt
  project_name: acme_insurance
