task_id: free_text_acme_lqls_011
status: ready
description: 'LQLS: Policy'
prompts:
- key: base
  prompt: 'Return all the policies we have by policy number, effective date and expiration
    date?


    Write a model called result.sql containing your answer.'
- key: with_sl
  prompt: 'Using the dbt semantic layer, answer this question:


    Return all the policies we have by policy number, effective date and expiration
    date?


    Write a model called result.sql containing your answer.'
author_name: dbt-labs
author_email: noreply@getdbt.com
difficulty: easy
tags:
- semantic-layer
- metricflow
- free-text
- acme-insurance
- lqls
test_setup: |-
  dbt run --select result
  python /scripts/fuzzy_compare.py result /seeds/solution__result.csv
variants:
- db_type: duckdb
  db_name: acme_insurance
  project_type: dbt
  project_name: acme_insurance
